import type { Metadata } from 'next';
import './globals.css';
import QueryProvider from './providers/QueryProvider';
import { Playfair_Display, Nanum_Myeongjo } from 'next/font/google';

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700', '800'],
  variable: '--font-playfair',
  display: 'swap',
});

const myeongjo = Nanum_Myeongjo({
  subsets: ['latin'],
  weight: ['400', '700', '800'],
  variable: '--font-myeongjo',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${playfair.variable} ${myeongjo.variable}`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
