name: Gemini PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Gemini PR Review
        uses: gemini-review/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
